# Generated by Django 5.2.5 on 2025-09-03 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('PLUS_EXPLICATION', "Plus d'explications")], default='EN_ATTENTE', max_length=20),
        ),
    ]
