# Generated by Django 5.2.5 on 2025-09-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_alter_conge_demandeur_alter_conge_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
